// protected/humhub/modules/space/widgets/react/assets/SpaceChooser.jsx
import React, { useState, useEffect, useRef, useCallback } from 'react';
import axios from 'axios';
import _ from 'lodash';
import SpaceChooserItem from './SpaceChooserItem';
import CreateSpace from './CreateSpace';

const csrfToken = document.querySelector('meta[name="csrf-token"]')?.content || '';

axios.defaults.withCredentials = true;
axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
axios.defaults.headers.common['X-CSRF-Token'] = csrfToken;

const SpaceChooser = ({
                          currentSpaceImage,
                          canCreateSpace,
                          canAccessDirectory,
                          directoryUrl,
                          createSpaceUrl,
                          remoteSearchUrl,
                          spaces: initialSpaces,
                          visibilityOptions,
                          joinPolicyOptions
                      }) => {
    const [isOpen, setIsOpen] = useState(false);
    const [searchQuery, setSearchQuery] = useState('');
    const [spaces, setSpaces] = useState(initialSpaces);
    const [showCreateForm, setShowCreateForm] = useState(false);
    const dropdownRef = useRef(null);
    const dropdownToggleRef = useRef(null);

    useEffect(() => {
        const handleClickOutside = (event) => {
            if (dropdownRef.current && !dropdownRef.current.contains(event.target) &&
                dropdownToggleRef.current && !dropdownToggleRef.current.contains(event.target)) {
                setIsOpen(false);
                setShowCreateForm(false);
            }
        };

        if (isOpen) {
            document.addEventListener('mousedown', handleClickOutside);
        }

        return () => {
            document.removeEventListener('mousedown', handleClickOutside);
        };
    }, [isOpen]);

    const debouncedSearch = useCallback(
        _.debounce(async (query) => {
            try {
                const response = await axios.get(remoteSearchUrl, {
                    params: {
                        keyword: query,
                        target: 'chooser'
                    }
                });

                if (response.data) {
                    setSpaces(response.data);
                }
            } catch (error) {
                console.error('Error fetching spaces:', error);
            }
        }, 300),
        [remoteSearchUrl]
    );

    useEffect(() => {
        if (!searchQuery) {
            setSpaces(initialSpaces);
            return;
        }

        debouncedSearch(searchQuery);
    }, [searchQuery, initialSpaces, debouncedSearch]);

    return (
        <>
            <a
                ref={dropdownToggleRef}
                href="#"
                id="space-menu"
                className="nav-link dropdown-toggle"
                onClick={(e) => {
                    e.preventDefault();
                    setIsOpen(!isOpen);
                }}
                aria-expanded={isOpen}
            >
                {currentSpaceImage || (
                    <div className='no-space'>
                        <i className='fa fa-dot-circle-o'/>
                        <br/>
                        My spaces
                    </div>
                )}
            </a>
            {isOpen && (
                <ul
                    ref={dropdownRef}
                    className="dropdown-menu"
                    id="space-menu-dropdown"
                    style={{ display: 'block' }}
                >
                    <li>
                        <form
                            action=""
                            className="dropdown-header dropdown-controls"
                            onSubmit={(e) => e.preventDefault()}
                        >
                            <div className={canAccessDirectory ? 'input-group' : ''}>
                                <input
                                    type="text"
                                    id="space-menu-search"
                                    className="form-control"
                                    autoComplete="off"
                                    placeholder="Search for spaces"
                                    title="Search for spaces"
                                    value={searchQuery}
                                    onChange={(e) => setSearchQuery(e.target.value)}
                                />

                                {canAccessDirectory && (
                                    <span id="space-directory-link" className="input-group-text">
                  <a href={directoryUrl}>
                      <i className="fa fa-sitemap"></i>
                  </a>
                </span>
                                )}

                                <div
                                    className="search-reset"
                                    id="space-search-reset"
                                    style={{ display: searchQuery ? 'block' : 'none' }}
                                    onClick={() => setSearchQuery('')}
                                >
                                    <i className="fa fa-times-circle"></i>
                                </div>
                            </div>
                        </form>
                    </li>

                    <li>
                        <hr className="dropdown-divider" />
                    </li>
                    <li>
                        <div id="space-menu-spaces" className="notLoaded hh-list">
                            {spaces.map((space) => <SpaceChooserItem key={space.guid} space={space} />)}
                        </div>
                    </li>
                    <li className="remoteSearch">
                        <div id="space-menu-remote-search" className="dropdown-item notLoaded hh-list"></div>
                    </li>

                    {canCreateSpace && (
                        <li>
                            <div className="dropdown-footer">
                                <button
                                    type="button"
                                    onClick={(e) => {
                                        e.preventDefault();
                                        setShowCreateForm(true);
                                    }}
                                    className="btn btn-accent col-lg-12"
                                >
                                    Create Space
                                </button>
                            </div>
                        </li>
                    )}
                </ul>
            )}
            {showCreateForm && (
                <div
                    ref={dropdownRef}
                    className="dropdown-menu"
                    style={{ display: 'block', width: '500px', maxWidth: '90vw' }}
                >
                    <CreateSpace
                        onCancel={() => {
                            setShowCreateForm(false);
                            setIsOpen(true);
                        }}
                        createSpaceUrl={createSpaceUrl}
                    />
                </div>
            )}
        </>
    );
};

export default SpaceChooser;

// protected/humhub/modules/space/widgets/vue/assets/SpaceChooser.vue
<script setup>
import http from 'humhub/http'
import {computed, onBeforeUnmount, ref, watch} from 'vue'

const props = defineProps({
    lazyLoad: {type: Boolean, default: true},
    lazySearchUrl: {type: String, required: true},
    remoteSearchUrl: {type: String, required: true},
    directoryUrl: {type: String, required: true},
    createSpaceUrl: {type: String, required: true},
    canCreateSpace: {type: Boolean, required: true},
    canAccessDirectory: {type: Boolean, required: true},
    currentSpaceImage: {type: String, default: ''},
    directoryIcon: {type: String, default: ''},
    noSpaceHtml: {type: String, required: true},
    spaces: {type: Array, default: () => []},
    text: {type: Object, required: true},
})

const dropdownRef = ref(null)
const dropdownToggleRef = ref(null)
const isOpen = ref(false)
const searchQuery = ref('')
const initialSpaces = ref(props.spaces)
const remoteSpaces = ref([])
const hasLoadedInitialSpaces = ref(!props.lazyLoad || props.spaces.length > 0)
const isLoadingInitialSpaces = ref(false)
const hasLoadedRemoteSpaces = ref(false)
const searchTimer = ref(null)
const requestId = ref(0)

const trimmedSearchQuery = computed(() => searchQuery.value.trim())
const showRemoteSearch = computed(() => trimmedSearchQuery.value.length >= 2)
const renderedSpaces = computed(() => showRemoteSearch.value ? remoteSpaces.value : initialSpaces.value)
const statusMessage = computed(() => {
    if (showRemoteSearch.value) {
        if (hasLoadedRemoteSpaces.value && remoteSpaces.value.length === 0) {
            return props.text.emptyResult
        }

        return ''
    }

    if (trimmedSearchQuery.value.length > 0) {
        return props.text.remoteAtLeastInput
    }

    if (hasLoadedInitialSpaces.value && initialSpaces.value.length === 0) {
        return props.text.emptyOwnResult
    }

    return ''
})

const clearSearchTimer = () => {
    if (searchTimer.value !== null) {
        window.clearTimeout(searchTimer.value)
        searchTimer.value = null
    }
}

const loadInitialSpaces = async () => {
    if (!props.lazyLoad || hasLoadedInitialSpaces.value || isLoadingInitialSpaces.value) {
        return
    }

    isLoadingInitialSpaces.value = true

    try {
        const {data} = await http.get(props.lazySearchUrl)
        initialSpaces.value = Array.isArray(data) ? data : []
        hasLoadedInitialSpaces.value = true
    } catch (error) {
        console.error('Error loading spaces:', error)
    } finally {
        isLoadingInitialSpaces.value = false
    }
}

const fetchRemoteSpaces = async (query) => {
    const currentRequestId = ++requestId.value
    hasLoadedRemoteSpaces.value = false

    try {
        const {data} = await http.get(props.remoteSearchUrl, {
            params: {
                keyword: query,
                target: 'chooser',
            },
        })

        if (currentRequestId !== requestId.value) {
            return
        }

        remoteSpaces.value = Array.isArray(data) ? data : []
        hasLoadedRemoteSpaces.value = true
    } catch (error) {
        if (currentRequestId !== requestId.value) {
            return
        }

        remoteSpaces.value = []
        hasLoadedRemoteSpaces.value = true
        console.error('Error fetching spaces:', error)
    }
}

const closeDropdown = () => {
    isOpen.value = false
    searchQuery.value = ''
    remoteSpaces.value = []
    hasLoadedRemoteSpaces.value = false
    clearSearchTimer()
}

const handleClickOutside = (event) => {
    if (dropdownRef.value?.contains(event.target) || dropdownToggleRef.value?.contains(event.target)) {
        return
    }

    closeDropdown()
}

const toggleDropdown = async (event) => {
    event.preventDefault()
    isOpen.value = !isOpen.value

    if (isOpen.value) {
        await loadInitialSpaces()
    } else {
        closeDropdown()
    }
}

watch(isOpen, (open) => {
    if (open) {
        document.addEventListener('mousedown', handleClickOutside)
    } else {
        document.removeEventListener('mousedown', handleClickOutside)
    }
})

watch(trimmedSearchQuery, (query) => {
    clearSearchTimer()

    if (query.length === 0) {
        remoteSpaces.value = []
        hasLoadedRemoteSpaces.value = false
        if (isOpen.value) {
            loadInitialSpaces()
        }
        return
    }

    if (query.length < 2) {
        remoteSpaces.value = []
        hasLoadedRemoteSpaces.value = false
        return
    }

    searchTimer.value = window.setTimeout(() => {
        fetchRemoteSpaces(query)
    }, 300)
})

onBeforeUnmount(() => {
    clearSearchTimer()
    document.removeEventListener('mousedown', handleClickOutside)
})
</script>

<template>
    <a
        ref="dropdownToggleRef"
        href="#"
        id="space-menu"
        class="nav-link dropdown-toggle"
        @click="toggleDropdown"
        :aria-expanded="isOpen"
    >
        <span v-if="currentSpaceImage" v-html="currentSpaceImage"></span>
        <span v-else v-html="noSpaceHtml"></span>
    </a>

    <ul
        v-if="isOpen"
        ref="dropdownRef"
        class="dropdown-menu show"
        id="space-menu-dropdown"
        style="display: block;"
    >
        <li>
            <form action="" class="dropdown-header dropdown-controls" @submit.prevent>
                <div :class="canAccessDirectory ? 'input-group' : ''">
                    <input
                        v-model="searchQuery"
                        type="text"
                        id="space-menu-search"
                        class="form-control"
                        autocomplete="off"
                        :placeholder="text.search"
                        :title="text.searchForSpaces"
                    >
                    <span v-if="canAccessDirectory" id="space-directory-link" class="input-group-text">
                        <a :href="directoryUrl" v-html="directoryIcon"></a>
                    </span>
                    <div
                        v-if="searchQuery"
                        class="search-reset"
                        id="space-search-reset"
                        @click="searchQuery = ''"
                    >
                        <i class="fa fa-times-circle"></i>
                    </div>
                </div>
            </form>
        </li>
        <li><hr class="dropdown-divider"></li>
        <li>
            <div id="space-menu-spaces" class="notLoaded hh-list">
                <div
                    v-for="(space) in renderedSpaces"
                    :key="space.guid"
                    style="display: contents;"
                    v-html="space.output"
                ></div>
                <div v-if="statusMessage" class="text-body-secondary">
                    {{ statusMessage }}
                </div>
            </div>
        </li>

        <li v-if="canCreateSpace">
            <div class="dropdown-footer">
                <a
                    href="#"
                    class="btn btn-accent col-lg-12"
                    data-action-click="ui.modal.load"
                    :data-action-url="createSpaceUrl"
                >
                    {{ text.createSpace }}
                </a>
            </div>
        </li>
    </ul>
</template>
